version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install process started
      - npm install --force
  build:
    commands:
      - echo build process started now
      - npm run build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now and invalidate cloudfront cache
      - cd dist
      - ls -la
      - aws s3 sync . s3://$ENV_APP_S3_BUCKET_NAME_FRONTEND --delete
